name: Live-Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    types: [opened]
    branches: ["live"]
jobs:
  Tests:
    secrets: inherit
    uses: ./.github/workflows/tests.yml  # use the callable tests job to run test
